Update SSL_CRM_VENU_cert_expiry.yml

diff --git a/.github/workflows/SSL_CRM_VENU_cert_expiry.yml b/.github/workflows/SSL_CRM_VENU_cert_expiry.yml
--- a/.github/workflows/SSL_CRM_VENU_cert_expiry.yml
+++ b/.github/workflows/SSL_CRM_VENU_cert_expiry.yml
@@ -1,165 +1,165 @@
-name: SSL_CERT_EXPIRY
+# name: SSL_CERT_EXPIRY
 
-on:
-  workflow_dispatch:
-  # Uncomment the below line to schedule the workflow to run every Monday at 1:30 PM UTC (7:00 PM IST)
-  # schedule:
-  #   - cron: '30 13 * * 1'
+# on:
+#   workflow_dispatch:
+#   # Uncomment the below line to schedule the workflow to run every Monday at 1:30 PM UTC (7:00 PM IST)
+#   # schedule:
+#   #   - cron: '30 13 * * 1'
 
-jobs:
-  check_ssl_expiry:
-    runs-on: ubuntu-latest
+# jobs:
+#   check_ssl_expiry:
+#     runs-on: ubuntu-latest
 
-    strategy:
-      matrix:
-        env: [stage, prod]  # Define the environments
+#     strategy:
+#       matrix:
+#         env: [stage, prod]  # Define the environments
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v3
 
-      - name: Set up Google Cloud SDK
-        uses: google-github-actions/setup-gcloud@v1
-        with:
-          version: 'latest'
+#       - name: Set up Google Cloud SDK
+#         uses: google-github-actions/setup-gcloud@v1
+#         with:
+#           version: 'latest'
 
-      - name: Set environment variables
-        run: |
-          # Function to check if a string is base64 encoded
-          is_base64() {
-            if [[ "$1" =~ ^[A-Za-z0-9+/]+={0,2}$ ]]; then
-              echo true
-            else
-              echo false
-            fi
-          }
+#       - name: Set environment variables
+#         run: |
+#           # Function to check if a string is base64 encoded
+#           is_base64() {
+#             if [[ "$1" =~ ^[A-Za-z0-9+/]+={0,2}$ ]]; then
+#               echo true
+#             else
+#               echo false
+#             fi
+#           }
       
-          # Choose service account key and project ID based on environment
-          if [ "${{ matrix.env }}" == "dev" ]; then
-            sa_key="${{ secrets.GCP_SERVICE_ACCOUNT_KEY_DEV }}"
-            project_id="${{ secrets.GCP_PROJECT_ID_DEV }}"
-            slack_url="${{ secrets.SLACK_WEBHOOK_URL_DEV }}"
-          elif [ "${{ matrix.env }}" == "test" ]; then
-            sa_key="${{ secrets.GCP_SERVICE_ACCOUNT_KEY_TEST }}"
-            project_id="${{ secrets.GCP_PROJECT_ID_TEST }}"
-            slack_url="${{ secrets.SLACK_WEBHOOK_URL_TEST }}"
-          elif [ "${{ matrix.env }}" == "stage" ]; then
-            sa_key="${{ secrets.GCP_SA_KEY_STAGE_PLAIN }}"
-            project_id="${{ secrets.GCP_PROJECT_ID_STAGE }}"
-            slack_url="${{ secrets.SLACK_WEBHOOK_URL_STAGE }}"
-          elif [ "${{ matrix.env }}" == "prod" ]; then
-            sa_key="${{ secrets.GCP_SA_KEY_PROD }}"
-            project_id="${{ secrets.GCP_PROJECT_ID_PROD_PLAIN }}"
-            slack_url="${{ secrets.SLACK_WEBHOOK_URL_PROD }}"
-          fi
+#           # Choose service account key and project ID based on environment
+#           if [ "${{ matrix.env }}" == "dev" ]; then
+#             sa_key="${{ secrets.GCP_SERVICE_ACCOUNT_KEY_DEV }}"
+#             project_id="${{ secrets.GCP_PROJECT_ID_DEV }}"
+#             slack_url="${{ secrets.SLACK_WEBHOOK_URL_DEV }}"
+#           elif [ "${{ matrix.env }}" == "test" ]; then
+#             sa_key="${{ secrets.GCP_SERVICE_ACCOUNT_KEY_TEST }}"
+#             project_id="${{ secrets.GCP_PROJECT_ID_TEST }}"
+#             slack_url="${{ secrets.SLACK_WEBHOOK_URL_TEST }}"
+#           elif [ "${{ matrix.env }}" == "stage" ]; then
+#             sa_key="${{ secrets.GCP_SA_KEY_STAGE_PLAIN }}"
+#             project_id="${{ secrets.GCP_PROJECT_ID_STAGE }}"
+#             slack_url="${{ secrets.SLACK_WEBHOOK_URL_STAGE }}"
+#           elif [ "${{ matrix.env }}" == "prod" ]; then
+#             sa_key="${{ secrets.GCP_SA_KEY_PROD }}"
+#             project_id="${{ secrets.GCP_PROJECT_ID_PROD_PLAIN }}"
+#             slack_url="${{ secrets.SLACK_WEBHOOK_URL_PROD }}"
+#           fi
       
-          # Check if service account key is already base64-encoded
-          if [ "$(is_base64 "$sa_key")" == "true" ]; then
-            echo "GCP_SERVICE_ACCOUNT_KEY=$sa_key" >> $GITHUB_ENV
-          else
-            # If not, base64 encode it
-            echo "GCP_SERVICE_ACCOUNT_KEY=$(echo "$sa_key" | base64)" >> $GITHUB_ENV
-          fi
+#           # Check if service account key is already base64-encoded
+#           if [ "$(is_base64 "$sa_key")" == "true" ]; then
+#             echo "GCP_SERVICE_ACCOUNT_KEY=$sa_key" >> $GITHUB_ENV
+#           else
+#             # If not, base64 encode it
+#             echo "GCP_SERVICE_ACCOUNT_KEY=$(echo "$sa_key" | base64)" >> $GITHUB_ENV
+#           fi
       
-          # Export other environment variables
-          echo "GCP_PROJECT_ID=$project_id" >> $GITHUB_ENV
-          echo "SLACK_WEBHOOK_URL=$slack_url" >> $GITHUB_ENV
-          echo "ENVIRONMENT=${{ matrix.env }}" >> $GITHUB_ENV
+#           # Export other environment variables
+#           echo "GCP_PROJECT_ID=$project_id" >> $GITHUB_ENV
+#           echo "SLACK_WEBHOOK_URL=$slack_url" >> $GITHUB_ENV
+#           echo "ENVIRONMENT=${{ matrix.env }}" >> $GITHUB_ENV
 
-      - name: Authenticate to Google Cloud (with base64 check)
-        run: |
-          # Check if GCP_SERVICE_ACCOUNT_KEY is base64 encoded by trying to decode it
-          echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > /dev/null 2>&1
-          if [ $? -ne 0 ]; then
-            # It's not base64, so encode it
-            echo "GCP_SERVICE_ACCOUNT_KEY is in plain JSON, encoding it."
-            echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" | base64 > $HOME/gcp-key.b64
-            base64 --decode $HOME/gcp-key.b64 > $HOME/gcp-key.json
-          else
-            # It's already base64, so decode it
-            echo "GCP_SERVICE_ACCOUNT_KEY is already base64 encoded."
-            echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcp-key.json
-          fi
-          # Authenticate using the decoded key
-          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
-          gcloud config set project ${{ env.GCP_PROJECT_ID }}
+#       - name: Authenticate to Google Cloud (with base64 check)
+#         run: |
+#           # Check if GCP_SERVICE_ACCOUNT_KEY is base64 encoded by trying to decode it
+#           echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > /dev/null 2>&1
+#           if [ $? -ne 0 ]; then
+#             # It's not base64, so encode it
+#             echo "GCP_SERVICE_ACCOUNT_KEY is in plain JSON, encoding it."
+#             echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" | base64 > $HOME/gcp-key.b64
+#             base64 --decode $HOME/gcp-key.b64 > $HOME/gcp-key.json
+#           else
+#             # It's already base64, so decode it
+#             echo "GCP_SERVICE_ACCOUNT_KEY is already base64 encoded."
+#             echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcp-key.json
+#           fi
+#           # Authenticate using the decoded key
+#           gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
+#           gcloud config set project ${{ env.GCP_PROJECT_ID }}
 
-      - name: Install gke-gcloud-auth-plugin
-        run: |
-          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
-          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
-          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
-          sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
+#       - name: Install gke-gcloud-auth-plugin
+#         run: |
+#           sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
+#           echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
+#           curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/cloud.google.gpg > /dev/null
+#           sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
 
-      - name: Get GKE cluster credentials for all clusters
-        run: |
-          # Read clusters into arrays
-          readarray -t CLUSTER_NAMES < <(gcloud container clusters list --format="value(name)")
-          readarray -t CLUSTER_ZONES < <(gcloud container clusters list --format="value(location)")
+#       - name: Get GKE cluster credentials for all clusters
+#         run: |
+#           # Read clusters into arrays
+#           readarray -t CLUSTER_NAMES < <(gcloud container clusters list --format="value(name)")
+#           readarray -t CLUSTER_ZONES < <(gcloud container clusters list --format="value(location)")
           
-          # Loop over each cluster
-          for i in "${!CLUSTER_NAMES[@]}"; do
-            CLUSTER_NAME="${CLUSTER_NAMES[i]}"
-            CLUSTER_ZONE="${CLUSTER_ZONES[i]}"
-            echo "Fetching credentials for Cluster Name: ${CLUSTER_NAME} in Zone: ${CLUSTER_ZONE}"
-            gcloud container clusters get-credentials "${CLUSTER_NAME}" --zone "${CLUSTER_ZONE}"
-          done
+#           # Loop over each cluster
+#           for i in "${!CLUSTER_NAMES[@]}"; do
+#             CLUSTER_NAME="${CLUSTER_NAMES[i]}"
+#             CLUSTER_ZONE="${CLUSTER_ZONES[i]}"
+#             echo "Fetching credentials for Cluster Name: ${CLUSTER_NAME} in Zone: ${CLUSTER_ZONE}"
+#             gcloud container clusters get-credentials "${CLUSTER_NAME}" --zone "${CLUSTER_ZONE}"
+#           done
 
-      - name: Check SSL certificate expiry
-        run: |
-          # Get the list of ingress names, separated by commas
-          names=$(kubectl get ingress | awk 'NR > 1 {printf "%s,", $1}' | sed 's/,$//')
+#       - name: Check SSL certificate expiry
+#         run: |
+#           # Get the list of ingress names, separated by commas
+#           names=$(kubectl get ingress | awk 'NR > 1 {printf "%s,", $1}' | sed 's/,$//')
           
-          # Initialize the final message with the header
-          echo "Following are the INGRESS SSL certificates which will expire within ${{ env.ENVIRONMENT }} ENV:\n" > final_message.txt
+#           # Initialize the final message with the header
+#           echo "Following are the INGRESS SSL certificates which will expire within ${{ env.ENVIRONMENT }} ENV:\n" > final_message.txt
 
-          # Process each ingress name
-          IFS="," read -r -a name_array <<< "$names"
-          for name in "${name_array[@]}"; do
-            # Get the TLS certificate name from the ingress
-            tls_cert_name=$(kubectl describe ingress "$name" | awk '/TLS:/ {getline; print $1}')
+#           # Process each ingress name
+#           IFS="," read -r -a name_array <<< "$names"
+#           for name in "${name_array[@]}"; do
+#             # Get the TLS certificate name from the ingress
+#             tls_cert_name=$(kubectl describe ingress "$name" | awk '/TLS:/ {getline; print $1}')
 
-            # Retrieve and decode the certificate
-            certificate_data=$(kubectl get secrets "$tls_cert_name" -o=json | jq -r '.data."tls.crt"')
-            actual_cert=$(echo "$certificate_data" | base64 -d | awk '/BEGIN CERTIFICATE/,/END CERTIFICATE/ {print; if (/END CERTIFICATE/) exit}')
+#             # Retrieve and decode the certificate
+#             certificate_data=$(kubectl get secrets "$tls_cert_name" -o=json | jq -r '.data."tls.crt"')
+#             actual_cert=$(echo "$certificate_data" | base64 -d | awk '/BEGIN CERTIFICATE/,/END CERTIFICATE/ {print; if (/END CERTIFICATE/) exit}')
 
-            # Extract the first domain from the certificate
-            dns=$(echo "$actual_cert" | openssl x509 -text -noout | awk '/DNS:/ {print $1; exit}' | sed -e 's/DNS://' -e 's/,$//' | grep -v localhost)
+#             # Extract the first domain from the certificate
+#             dns=$(echo "$actual_cert" | openssl x509 -text -noout | awk '/DNS:/ {print $1; exit}' | sed -e 's/DNS://' -e 's/,$//' | grep -v localhost)
 
-            # Extract the expiry date and calculate the remaining days
-            validity=$(echo "$actual_cert" | openssl x509 -text -noout | grep -E 'Not After')
-            expiry_date=$(date -d "$(echo "$validity" | sed 's/Not After : //')" +"%s")
-            current_date=$(date +"%s")
-            days_remaining=$(( (expiry_date - current_date) / (60*60*24) ))
+#             # Extract the expiry date and calculate the remaining days
+#             validity=$(echo "$actual_cert" | openssl x509 -text -noout | grep -E 'Not After')
+#             expiry_date=$(date -d "$(echo "$validity" | sed 's/Not After : //')" +"%s")
+#             current_date=$(date +"%s")
+#             days_remaining=$(( (expiry_date - current_date) / (60*60*24) ))
 
-            # Set the threshold for sending alerts
-            threshold_days=500
+#             # Set the threshold for sending alerts
+#             threshold_days=500
 
-            # Check if the certificate expiry is within the threshold
-            if [ "$days_remaining" -le "$threshold_days" ]; then
-              echo "Domain_name: $dns  Days Remaining: $days_remaining" >> final_message.txt
-              certificates_to_notify=true
-            fi
-          done
+#             # Check if the certificate expiry is within the threshold
+#             if [ "$days_remaining" -le "$threshold_days" ]; then
+#               echo "Domain_name: $dns  Days Remaining: $days_remaining" >> final_message.txt
+#               certificates_to_notify=true
+#             fi
+#           done
 
-          # Check if there are certificates to notify about
-          if [ "$certificates_to_notify" = true ]; then
-            echo "certificates_to_notify=true" >> $GITHUB_ENV
-            cat final_message.txt > FINAL_MESSAGE.txt
-          else
-            echo "No certificates are expiring within $threshold_days days."
-          fi
+#           # Check if there are certificates to notify about
+#           if [ "$certificates_to_notify" = true ]; then
+#             echo "certificates_to_notify=true" >> $GITHUB_ENV
+#             cat final_message.txt > FINAL_MESSAGE.txt
+#           else
+#             echo "No certificates are expiring within $threshold_days days."
+#           fi
 
-      - name: Send Slack Alert if certificates are expiring
-        if: ${{ env.certificates_to_notify == 'true' }}
-        run: |
-          webhook_url="${{ env.SLACK_WEBHOOK_URL }}"
-          message_content=$(cat FINAL_MESSAGE.txt)
-          curl -X POST -H 'Content-type: application/json' --data "{ 'text': 'SSL CERTIFICATE EXPIRY:\n\n$message_content'}" "$webhook_url"
+#       - name: Send Slack Alert if certificates are expiring
+#         if: ${{ env.certificates_to_notify == 'true' }}
+#         run: |
+#           webhook_url="${{ env.SLACK_WEBHOOK_URL }}"
+#           message_content=$(cat FINAL_MESSAGE.txt)
+#           curl -X POST -H 'Content-type: application/json' --data "{ 'text': 'SSL CERTIFICATE EXPIRY:\n\n$message_content'}" "$webhook_url"
 
-      - name: Send alert to Slack on job failure
-        if: ${{ failure() }}
-        run: |
-          webhook_url="${{ env.SLACK_WEBHOOK_URL }}"
-          message="The SSL certificate expiry check JOB failed for ${{ env.ENVIRONMENT }} environment."
-          curl -X POST -H 'Content-type: application/json' --data "{ 'text': 'SSL CERTIFICATE EXPIRY:\n\n$message'}" "$webhook_url
+#       - name: Send alert to Slack on job failure
+#         if: ${{ failure() }}
+#         run: |
+#           webhook_url="${{ env.SLACK_WEBHOOK_URL }}"
+#           message="The SSL certificate expiry check JOB failed for ${{ env.ENVIRONMENT }} environment."
+#           curl -X POST -H 'Content-type: application/json' --data "{ 'text': 'SSL CERTIFICATE EXPIRY:\n\n$message'}" "$webhook_url
