Update SSL_CRM_VENU_cert_expiry.yml

diff --git a/.github/workflows/SSL_CRM_VENU_cert_expiry.yml b/.github/workflows/SSL_CRM_VENU_cert_expiry.yml
--- a/.github/workflows/SSL_CRM_VENU_cert_expiry.yml
+++ b/.github/workflows/SSL_CRM_VENU_cert_expiry.yml
@@ -49,10 +49,15 @@ jobs:
 
       - name: Authenticate to Google Cloud
         run: |
-          # echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcp-key.json
-          echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" > $HOME/gcp-key.json
+          # Attempt to decode the service account key. If decoding fails, use the key as-is.
+          echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcp-key.json 2>/dev/null || echo "${{ env.GCP_SERVICE_ACCOUNT_KEY }}" > $HOME/gcp-key.json
+          
+          # Authenticate to Google Cloud using the decoded or raw service account key
           gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
+          
+          # Set the GCP project ID
           gcloud config set project ${{ env.GCP_PROJECT_ID }}
+          
 
       - name: Install gke-gcloud-auth-plugin
         run: |
