Update test_sql_auth_connect.yml

diff --git a/.github/workflows/test_sql_auth_connect.yml b/.github/workflows/test_sql_auth_connect.yml
--- a/.github/workflows/test_sql_auth_connect.yml
+++ b/.github/workflows/test_sql_auth_connect.yml
@@ -43,20 +43,43 @@ jobs:
 
       - name: Fetch SQL Auth Proxy Version
         run: |
-          while read instance_group; do
-            # Get the location (region or zone) of the instance group
-            location=$(gcloud compute instance-groups managed list --filter="name=$instance_group" --format="value(location)" --project="${{ env.GCP_PROJECT_ID }}")
+          # Fetch instance groups and check if the file is created
+          gcloud compute instance-groups managed list --filter="name:(*sql auth proxy*)" --format="value(name, location)" --project="${{ env.GCP_PROJECT_ID }}" > instance_groups.txt
+          if [ ! -s instance_groups.txt ]; then
+            echo "No SQL Auth Proxy instance groups found."
+            exit 1
+          fi
 
+          # Read the instance groups and process each one
+          while IFS=',' read -r instance_group location; do
+            if [ -z "$instance_group" ]; then
+              echo "Error: Instance group is empty."
+              exit 1
+            fi
+            
+            echo "Processing instance group: $instance_group in location: $location"
+            
             # Describe the instance group with the correct region or zone
             instance_template=$(gcloud compute instance-groups managed describe "$instance_group" --region="$location" --format="value(instanceTemplate)" --project="${{ env.GCP_PROJECT_ID }}")
-            
+
+            if [ -z "$instance_template" ]; then
+              echo "Error: Instance template for $instance_group not found."
+              exit 1
+            fi
+
             # Fetch the SQL Auth Proxy version from the instance template
             version=$(gcloud compute instance-templates describe "$instance_template" --format="get(properties.metadata.items)" | grep -oP 'cloud-sql-proxy/v\K[0-9]+\.[0-9]+\.[0-9]+')
+
+            if [ -z "$version" ]; then
+              echo "Error: Version not found for instance group $instance_group."
+              exit 1
+            fi
 
             # Write the information to a file for Slack notification
             echo "*Instance Group*: $instance_group" > proxy_version_${{ matrix.environment }}.txt
             echo "*Version*: $version" >> proxy_version_${{ matrix.environment }}.txt
           done < instance_groups.txt
+
 
 
       - name: Compare and Check for SQL Auth Proxy Version Updates
