Update test_sql_auth_connect.yml

diff --git a/.github/workflows/test_sql_auth_connect.yml b/.github/workflows/test_sql_auth_connect.yml
--- a/.github/workflows/test_sql_auth_connect.yml
+++ b/.github/workflows/test_sql_auth_connect.yml
@@ -86,9 +86,14 @@ jobs:
       - name: Compare and Check for SQL Auth Proxy Version Updates
         run: |
           echo "Fetching latest version from GitHub..."
-          response=$(curl --silent "https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-proxy/releases/latest")
-          echo "Response: $response"  # Debug output
+          response=$(curl --silent --fail "https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-proxy/releases/latest")
+          
+          if [ $? -ne 0 ]; then
+              echo "Error: Failed to fetch the latest version from GitHub."
+              exit 1
+          fi
 
+          echo "Response: $response"  # Debug output
           latest_version=$(echo "$response" | jq -r .tag_name 2>/dev/null | sed 's/^v//')
           
           if [ $? -ne 0 ]; then
@@ -105,7 +110,12 @@ jobs:
           echo "Latest version is: $latest_version"
 
           current_version=$(grep -oP 'Version: \K[0-9]+\.[0-9]+\.[0-9]+' proxy_version_${{ matrix.environment }}.txt || echo "N/A")
-          echo "Current version is: $current_version"  # Debug output
+          echo "Current version fetched from file: $current_version"  # Debug output
+          
+          if [ "$current_version" = "N/A" ]; then
+              echo "Error: Current version is not available."
+              exit 1
+          fi
           
           if [[ "$latest_version" != "$current_version" ]]; then
             echo "*Latest Version*: $latest_version" >> proxy_version_${{ matrix.environment }}.txt
@@ -119,14 +129,15 @@ jobs:
           if [ -f proxy_version_${{ matrix.environment }}.txt ]; then
             message=$(cat proxy_version_${{ matrix.environment }}.txt)
             curl -X POST -H 'Content-type: application/json' --data "{
-              'text': 'GCP SQL AUTH PROXY VERSION CHECK (${{ matrix.environment }}):\n\n$message'
+              \"text\": \"GCP SQL AUTH PROXY VERSION CHECK (${{ matrix.environment }}):\n\n$message\"
             }" "${{ env.SLACK_WEBHOOK_URL }}"
           else
             echo "No alert to send for ${{ matrix.environment }}."
+          fi
       
       - name: Send alert to Slack on job failure
         if: failure()
         run: |
           curl -X POST -H 'Content-type: application/json' --data "{
-            'text': 'GCP SQL AUTH PROXY VERSION CHECK:\n\nThe workflow for ${{ matrix.environment }} failed.'
+            \"text\": \"GCP SQL AUTH PROXY VERSION CHECK:\n\nThe workflow for ${{ matrix.environment }} failed.\"
           }" "${{ env.SLACK_WEBHOOK_URL }}"
